apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playlist-recommender
  namespace: argocd
spec:
  project: matheuslima-project
  source:
    repoURL: https://github.com/vazleal/devops-tp2.git
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: matheuslima
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
