apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc
  namespace: matheuslima
spec:
  storageClassName: default-storage-class-matheuslima
  selector:
    matchLabels:
      namespace: matheuslima
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
