apiVersion: v1
kind: Service
metadata:
  name: playlist-api-service
  namespace: matheuslima
spec:
  selector:
    app: playlist-api
  ports:
    - name: http
      protocol: TCP
      port: 30502
      targetPort: 50023
